### ISSUE TITLE
Todo List...

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#38]
So I have been running on Trello for a while, but it seems people would prefer a todo list to be here, which makes sense. So here we are. I haven't included everything I have done so far....

### Source code management and conventions
- [x] Migrate to Allman brace styling to comply with Microsoft conventions

### Data
- [ ] Recipes **(Currently Working on)**
- [x] Migrations pipeline
- [x] New content type system
- [ ] Add DB Choice to Setup
- [x] Map Reduce API
- [ ] Content Stores
    - [x] InMemory
    - [x] Sql
    - [x] Memory Mapped file (Lightning.NET)
    - [x] Flat file
    - [ ] Cache
    - [ ] Distributed cache

### Content Management
- [ ] Shrink IContentManager and make methods ASync
- [ ] Split the manager

### UI
- [x] Themes
- [x] Layouts
- [ ] Admin UI
- [x] Shapes

### Caching
- [x] Caching abstraction https://github.com/aspnet/Caching 
- [x] Business data caching
- [x] Distributed caching api (https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Framework.Caching.Abstractions/IDistributedCache.cs)
    - [x] memory cache module https://github.com/aspnet/Caching/tree/dev/src/Microsoft.Framework.Caching.Memory
    - [x] Redis cache module https://github.com/aspnet/Caching/tree/dev/src/Microsoft.Framework.Caching.Redis

### Packaging
- [x] MyGet building core packages (https://www.myget.org/gallery/brochard)

### Tooling
- [x] Command-line tooling
- [x] Setup **(Partial)**
- [ ] Host Config file

### Localization
- [ ] Create abstraction https://github.com/aspnet/localization
- [ ] App Localization (of admin panel, modules, themes)
- [ ] Content Localization (multi-lingual sites)
- [ ] T-strings
    - [x] Make T() available for views
    - [ ] Migrate all strings to T-strings

### Events 
- [x] Event Bus
- [x] Event model (a.k.a. plugins)
- [x] IEventHandler
- [ ] Migrate to use CoreFx Observer/Observable pattern

### Logging
- [x] Logging abstraction
- [x] Console logging provider
- [ ] Configuration from Host Config

### Indexing
- [ ] Query Storage Changes (Eager Indexing)

### Framework
- [ ] Work Context
- [ ] Migrate unit tests
- [x] Extensibility of Module Folders
- [ ] Extensions
    - [x] Load
    - [ ] Unload
- [ ] Rewrite file system access using https://github.com/aspnet/FileSystem **(currently working on)**
- [ ] Add folder monitoring to dynamic extension loader (*Easy One*)
- [ ] Sort out framework namespaces  (*Easy One*)
- [ ] Add "tags": [ "" ], "projectUrl": "",  "licenseUrl": "", to all project.json files with relevant information
- [ ] Add Autofac to deal out Request Services

### Configuration
- [ ] Make ShellSettingsManager use IOptions for the FileName and Path to Tenants (*Easy One*)
- [ ] Set environment when starting application (*Easy One*)

### Nice to have if someone wants to give it a go (but not a priority)
*Data*
  - [ ] Dapper content store module
  - [ ] Github content store module

*IoC*
  - [ ] DryIoc (When CoreClr Compliant)

*Packaging*
  - [ ] Theme packaging
  - [ ] Module packaging

*EventBus*
  - [ ] Migrate to use CoreFx Observer/Observable pattern

*Indexing*
  - [ ] Lucene (Only if CoreCLR compatible http://code972.com/blog/2015/01/79-lucene-nets-new-future-and-status-update)
  - [ ] Create IContentQueryStore against Lucene

*Caching*
  - [ ] SqlServer cache module https://github.com/aspnet/Caching/tree/dev/src/Microsoft.Framework.Caching.SqlServer

*Security*
  - [ ] SSL
  - [ ] CORS middleware

**Comment by omidkrad** [comment]
Hi guys, I've been exploring the Aurelia project (http://aurelia.io) which is a new JS framework based on the latest web standards that also makes creating Single Page Apps really easy. I think Orchard 2 can get a lot of inspirations from it and maybe use it in the project.

**Comment by omidkrad** [comment]
Another project that I wanted to point out is [ASP.NET MVC Boierplate](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate). It is:

> A professional ASP.NET MVC template for building secure, fast, robust and adaptable web applications or sites. It provides the minimum amount of code required on top of the default MVC template provided by Microsoft.

The MVC boilerplate comes with many security features pre-setup on it that I think every web application should use. It would be great to have some of these in Orchard too so that we can just enable them like features.

**Comment by sebastienros** [comment]
@omidkrad Have you used Orchard 1 by the past?

> it comes with many security features pre-setup on it

**Comment by omidkrad** [comment]
@sebastienros yes, I know Orchard has some good security features, and that there are a lot of good modules. But I find it overwhelming when I dive in the gallery. I like MVC Boilerplate's approach a little better that it provides a [Checklist](https://htmlpreview.github.io/?https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/Source/MVC5/Boilerplate.Web.Mvc5.Sample/ReadMe.html) of the important things you need to do for tightening up security on the pre-installed security features and else just after creating a new project.

**Comment by sebastienros** [comment]
@omidkrad Everything security wise is already out of the box. User management, permissions, roles, forms auth. Is there any specific feature you found in boilerplate that is not by default in Orchard you are referring about?

**Comment by omidkrad** [comment]
@sebastienros Content Security Policy and force HTTPS for example.

**Comment by abdullahsalem** [comment]
@Jetski5822 I would like to add a specific **Todo** item under the **UI** list, which is:
- [ ] RTL support
<br > I believe that **Localization** and **Supporting RTL** should be considered, side by side.
